{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: trust-manager-webhook-exception
  namespace: cert-manager
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    6443:
      mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: trust-manager
{{- end }}