tasks:
  - name: all
    actions:
      - task: health-check
      - task: trust-bundle

  - name: health-check
    actions:
      - description: Trust Manager Health Check
        wait:
          cluster:
            kind: Deployment
            name: trust-manager
            namespace: cert-manager
            condition: Available

  - name: trust-bundle
    description: Test creating a bundle of certs
    actions:
      - cmd: |
          ./uds zarf package create --confirm
        dir: tests/trustbundle
      - cmd: |
          openssl req -x509 -newkey rsa:4096 -keyout testCA.key \
            -out testCA.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
        dir: tests/trustbundle
      - cmd: |
          ./uds zarf package deploy \
            --set CUSTOM_CA_CHAIN=$(cat testCA.pem | base64 -w 0) \
            zarf-package-trust-bundle-${UDS_ARCH}-0.0.1.tar.zst \
            --confirm
        dir: tests/trustbundle
      - description: Ensure configmap is created in zarf namespace
        wait:
          cluster:
            kind: configmap
            name: trust-bundle
            namespace: zarf
      - cmd: |
          rm testCA.key testCA.pem
        dir: tests/trustbundle
